apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: "/data/grafana"
    server: 192.186.1.11
