apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  nfs:
    path: "/data/grafana"
    server: 192.186.1.11