apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-pv
  labels:
    type: local
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""
  nfs:
    path: "/data/grafana"
    server: 192.186.1.11