apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-storage
spec:
  capacity:
    storage: 25Gi
  storageClassName: "local-storage"
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 192.168.1.11
    path: "/data/prom"
  mountOptions:
    - nfsvers=4.2
