apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-storage
  labels:
    app: grafana-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 192.168.1.11
    path: "/data/grafana"
  mountOptions:
    - nfsvers=4.2
