apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-storage
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.11
    path: "/data/grafana"
  mountOptions:
    - nfsvers=4.2
