apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-storage
  labels:
    app: prom-nfs
spec:
  capacity:
    storage: 150Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 192.168.1.11
    path: "/data/grafana"
  mountOptions:
    - nfsvers=4.2
